//! CLI entry — keep thin; subcommands in cmds/, clap defs in cli.rs / ops_subs.rs.

mod cli;
mod cli_subs;
mod cmds;
mod ops_subs;

use clap::Parser;
use cli::{Cli, Cmd};
use cli_subs::{ClaimSub, CloseoutSub, LedgerSub, ParseSub, ProgressSub, RetroSub, SourceSub};
use cmds::*;
use std::process::ExitCode;

fn main() -> ExitCode {
    match Cli::parse().cmd {
        Cmd::Gate {
            url,
            rules,
            l0_only,
            tcp_timeout,
            l2_timeout,
        } => run_gate(GateArgs {
            url,
            rules,
            l0_only,
            tcp_timeout,
            l2_timeout,
        }),
        Cmd::RepairDry {
            url,
            rules,
            l0_only,
            tcp_timeout,
            l2_timeout,
            html,
        } => run_repair_dry(RepairDryArgs {
            url,
            rules,
            l0_only,
            tcp_timeout,
            l2_timeout,
            html,
        }),
        Cmd::Repair {
            url,
            urls_file,
            mode,
            limit,
            rules,
            l0_only,
            tcp_timeout,
            l2_timeout,
            dry_run,
            no_verify,
            html,
            no_prefetch,
            key,
            skip_diagnose,
        } => run_repair(RepairArgs {
            url,
            urls_file,
            mode,
            limit,
            rules,
            l0_only,
            tcp_timeout,
            l2_timeout,
            dry_run,
            no_verify,
            html,
            prefetch: !no_prefetch,
            key,
            skip_diagnose,
        }),
        Cmd::Diagnose {
            url,
            key,
            rules,
            l0_only,
            tcp_timeout,
            l2_timeout,
            debug_file,
            out,
        } => run_diagnose(DiagnoseArgs {
            url,
            key,
            rules,
            l0_only,
            tcp_timeout,
            l2_timeout,
            debug_file,
            out,
        }),
        Cmd::Fetch {
            url,
            page,
            dump_dir,
            out,
        } => run_fetch(FetchArgs {
            url,
            page,
            dump_dir,
            out,
        }),
        Cmd::Probe {
            base_url,
            html,
            html_file,
            key,
            js_engine,
        } => run_probe(ProbeArgs {
            base_url,
            html,
            html_file,
            key,
            js_engine,
        }),
        Cmd::Migrate {
            from_url,
            to_url,
            dry_run,
            keep_old,
            verify,
            enable,
            out,
        } => run_migrate(MigrateArgs {
            from_url,
            to_url,
            dry_run,
            keep_old,
            verify,
            enable,
            out,
        }),
        Cmd::Hunt {
            url,
            seeds,
            probe,
            l2_timeout,
            rules,
            out,
        } => run_hunt(HuntArgs {
            url,
            seeds,
            probe,
            l2_timeout,
            rules,
            out,
        }),
        Cmd::Progress { cmd } => match cmd {
            ProgressSub::Status {
                index,
                rules,
                l0_only,
                goal,
            } => run_progress(ProgressArgs {
                cmd: "status".into(),
                index,
                rules,
                l0_only,
                goal,
            }),
            ProgressSub::Next {
                index,
                rules,
                l0_only,
                goal,
            } => run_progress(ProgressArgs {
                cmd: "next".into(),
                index,
                rules,
                l0_only,
                goal,
            }),
        },
        Cmd::Ledger { cmd } => match cmd {
            LedgerSub::Append {
                url,
                step,
                result,
                note,
                waste,
            } => run_ledger(LedgerCmd::Append {
                url,
                step,
                result,
                note,
                waste,
            }),
            LedgerSub::Show { limit } => run_ledger(LedgerCmd::Show { limit }),
        },
        Cmd::Ewma { prev, suggested } => run_ewma(prev, suggested),
        Cmd::ProbeScore {
            query,
            status,
            html,
        } => run_probe_score(&query, status, html),
        Cmd::VideoRoute { url, routes } => run_video_route(&url, routes),
        Cmd::Closeout { cmd } => match cmd {
            CloseoutSub::Pending => run_closeout(CloseoutArgs {
                cmd: "pending".into(),
                trap: None,
                skill_fix: false,
            }),
            CloseoutSub::Gate { trap, skill_fix } => run_closeout(CloseoutArgs {
                cmd: "gate".into(),
                trap: Some(trap),
                skill_fix,
            }),
            CloseoutSub::SyncSkill => run_closeout(CloseoutArgs {
                cmd: "sync-skill".into(),
                trap: None,
                skill_fix: false,
            }),
            CloseoutSub::Status => run_closeout(CloseoutArgs {
                cmd: "status".into(),
                trap: None,
                skill_fix: false,
            }),
        },
        Cmd::Retro { cmd } => match cmd {
            RetroSub::Append {
                url,
                status,
                msg,
                name,
                respond_time,
                waste_s,
                trap,
                harness,
                script_fix,
                skill_fix,
                seal,
            } => run_retro(RetroArgs {
                url,
                status,
                msg,
                name,
                respond_time,
                waste_s,
                trap,
                harness,
                script_fix,
                skill_fix,
                seal,
            }),
        },
        Cmd::Discover {
            write,
            timeout,
            config,
            sync_cursor,
        } => run_discover(DiscoverArgs {
            write,
            timeout,
            config,
            sync_cursor,
        }),
        Cmd::Check { cmd } => run_check_sub(cmd),
        Cmd::Queue { cmd } => run_queue_sub(cmd),
        Cmd::Pattern { cmd } => run_pattern_sub(cmd),
        Cmd::Db { cmd } => run_db_sub(cmd),
        Cmd::Cache { cmd } => run_cache_sub(cmd),
        Cmd::Knowledge { cmd } => run_knowledge_sub(cmd),
        Cmd::Parse { cmd } => match cmd {
            ParseSub::Rule { rule } => run_parse(ParseCmd::Rule { rule }),
            ParseSub::Url { url } => run_parse(ParseCmd::Url { url }),
        },
        Cmd::Parity { suite } => run_parity(ParityArgs { suite }),
        Cmd::Wave {
            urls_file,
            keyword,
            thread_count,
            patch_workers,
            timeout_ms,
            check_discovery,
            disable_dropped,
            out,
            rules,
            l2_timeout,
        } => run_wave_cmd(WaveArgs {
            urls_file,
            keyword,
            thread_count,
            patch_workers,
            timeout_ms,
            check_discovery,
            disable_dropped,
            out,
            rules,
            l2_timeout,
        }),
        Cmd::Harvest {
            fails,
            limit,
            keyword,
            thread_count,
            timeout_ms,
            out,
        } => run_harvest_cmd(HarvestArgs {
            fails: fails.unwrap_or_else(source_check::default_fails_path),
            limit,
            keyword,
            thread_count,
            timeout_ms,
            out,
        }),
        Cmd::Serial {
            urls_file,
            limit,
            keyword,
            l0_only,
            tcp_timeout,
            l2_timeout,
            rules,
            rebuild_queue,
            auto_retro,
            out,
        } => run_serial_cmd(SerialArgs {
            urls_file,
            limit,
            keyword,
            l0_only,
            tcp_timeout,
            l2_timeout,
            rules,
            rebuild_queue,
            auto_retro,
            out,
        }),
        Cmd::Bench {
            urls_file,
            keyword,
            thread_count,
            patch_workers,
            timeout_ms,
            disable_dropped,
            out,
            rules,
            l2_timeout,
        } => run_bench_cmd(BenchArgs {
            urls_file,
            keyword,
            thread_count,
            patch_workers,
            timeout_ms,
            disable_dropped,
            out,
            rules,
            l2_timeout,
        }),
        Cmd::DeepWave {
            urls_file,
            keyword,
            budget_s,
            out,
        } => run_deep_wave_cmd(DeepWaveArgs {
            urls_file,
            keyword,
            budget_s,
            out,
        }),
        Cmd::SearchWave {
            urls_file,
            keyword,
            workers,
            thread_count,
            timeout_ms,
            out,
        } => run_search_wave_cmd(SearchWaveArgs {
            urls_file,
            keyword,
            workers,
            thread_count,
            timeout_ms,
            out,
        }),
        Cmd::Goal15 {
            urls_file,
            keyword,
            rules,
            l0_only,
            tcp_timeout,
            l2_timeout,
            out,
        } => run_goal15_cmd(Goal15Args {
            urls_file,
            keyword,
            rules,
            l0_only,
            tcp_timeout,
            l2_timeout,
            out,
        }),
        Cmd::Source { cmd } => match cmd {
            SourceSub::Triage {
                url,
                fail_msg,
                out,
            } => run_source(SourceCmd::Triage {
                url,
                fail_msg,
                out,
            }),
            SourceSub::Fetch {
                url,
                page,
                dump_dir,
                out,
            } => run_source(SourceCmd::Fetch(FetchArgs {
                url,
                page,
                dump_dir,
                out,
            })),
            SourceSub::Verify {
                url,
                keyword,
                timeout_ms,
                auto_cooldown,
                cooldown,
                out,
            } => run_source(SourceCmd::Verify {
                url,
                keyword,
                timeout_ms,
                auto_cooldown,
                cooldown,
                out,
            }),
            SourceSub::Log {
                url,
                name,
                status,
                keyword,
                root_cause,
                check_json,
                out,
                index,
                agent,
            } => run_source(SourceCmd::Log {
                url,
                name,
                status,
                keyword,
                root_cause,
                check_json,
                out,
                index,
                agent,
            }),
            SourceSub::Index { from_log, index } => run_source(SourceCmd::Index { from_log, index }),
            SourceSub::Channel => run_source(SourceCmd::Channel),
        },
        Cmd::Claim { cmd } => match cmd {
            ClaimSub::Validate { check_json } => run_claim(ClaimCmd::Validate { check_json }),
            ClaimSub::AppendIndex {
                index,
                status,
                url,
                name,
                evidence,
                agent,
                root_cause,
            } => run_claim(ClaimCmd::AppendIndex {
                index,
                status,
                url,
                name,
                evidence,
                agent,
                root_cause,
            }),
        },
        Cmd::DebugVsCheck {
            url,
            key,
            out,
            no_ledger,
        } => run_debug_vs_check(DebugVsCheckArgs {
            url,
            key,
            out,
            no_ledger,
        }),
        Cmd::Version => run_version(),
    }
}
